print("Hello World!")
name = input("Please enter your name: ")
print("Hello, " + name + "!")
year = int(input("Please enter the year of your birth: "))
print("You are ", 2023 - year, "years old.")
height = float(input("Please enter your height in cm: "))
print("You are ", height / 100, "meters tall.")
